backend:
  name: git-gateway
  branch: master 


  media_folder: "static/images/uploads"
  public_folder: "images/uploads"

  collections:
    - name: "coding"
      label: "Coding"
      folder: "content/blog"
      create: true 
      slug: "{{year}}--{{slug}}"
      fields: 
        - {label: "Title", name: "title", widget: "string", required: true}
        - {label: "Publish Date", name: "date", widget: "date"}
        - {label: "Categoires", name: "categories", widget: "string"}
        - {label: "Author", name: author, widget: hidden, default: Moritz Lennartz}
        - {label: "Header Image", name: "image", widget: image, required: false}



